### ISSUE TITLE
Missing events

### ISSUE THREAD

**Issue by originalfoo** [thale5/LSM#14]
@thale5 : Elektrix did some investigations in to events on `LoadingManager.instance` and found some problems with LSM (the events work fine in vanilla). Copied below is a transcript from the `Skylines.Code` discord:

> **Elektrix** Today at 14:24  
> I first attempted the LoadingManager events, but I'm at this point pretty convinced that Loading Screen Mod ignores them. I'm going to test that right now, and if it does, I'll ask thale to add it  
> Yes, **Loading Screen Mod definitely ignores `LoadingManager.instance.m_simulationDataReady`**  
> **The other ones don't seem to fire in the loading process, which is unfortunate**  
> I used a very high quality test to make sure:

![image](https://user-images.githubusercontent.com/1386719/76686710-5551ec00-6615-11ea-82c7-5c6b2cba181b.png)

> The event definitely fires in vanilla  
> I think metadata is loaded before the Created() loadingextension hook from what I can tell in dnSpy  
> It looks like I'm going to want to insert code after line 264 of LoadLevelCoroutine with a transpiler, which is quite unfortunate.

![image](https://user-images.githubusercontent.com/1386719/76686721-6c90d980-6615-11ea-838e-e4181bcc3910.png)

----

If it helps with testing, my [**SequenceLogger** mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2018193885) (Steam workshop link) logs those events:

https://github.com/CitiesSkylinesMods/SequenceLogger/blob/master/SequenceLogger/SequenceLogger/Events/LoadingManagerEvents.cs

**Comment by thale5** [comment]
m_simulationDataReady is fired just before OnLevelLoaded, with LSM and without LSM.
As far as I know it has always worked the same. I tested with two mods like this:

```
public void OnCreated(ILoading loading)
{
    Singleton<LoadingManager>.instance.m_simulationDataReady += Test;
}

void Test()
{
    Util.DebugPrint("m_simulationDataReady");
}
```

And got the log output:

```
[LessSteam] m_simulationDataReady
[LSMT] m_simulationDataReady at 29377
[LSMT] Waiting at 29377
[LSMT] Mem 29377 7549 9475
[LSMT] OnLevelLoaded at 29990
```

m_levelPreLoaded is fired very early, before OnCreated.

m_metaDataReady is essential because the game hooks into it to call loading extensions (OnCreated). If m_metaDataReady stops working, mods stop working.

**Comment by originalfoo** [comment]
Hrm, yes, I am getting same results now:

```diff
SequenceLogger v1.1.0.37477
UserMod.ctor() static
UserMod.ctor() instance
UserMod.OnEnabled()
PluginManager.eventPluginsChanged
[135 repeat(s)]
LocaleManager.eventLocaleChanged
SceneManager.activeSceneChanged(, Startup)
SceneManager.sceneLoaded(Startup, Single)
SceneManager.sceneLoaded(LoadingAnimation, Additive)
SceneManager.sceneUnloaded(Startup)
SceneManager.sceneUnloaded(LoadingAnimation)
SceneManager.activeSceneChanged(, IntroScreen)
SceneManager.sceneLoaded(IntroScreen, Single)
SceneManager.sceneLoaded(IntroScreen2, Additive)
UserMod.OnSettingsUI()
SceneManager.sceneLoaded(MainMenu, Additive)
+ LoadingManager.instance.m_introLoaded
+ LoadingManager.instance.m_levelPreLoaded
SceneManager.sceneUnloaded(IntroScreen)
SceneManager.sceneUnloaded(IntroScreen2)
SceneManager.sceneUnloaded(MainMenu)
SceneManager.activeSceneChanged(, Game)
SceneManager.sceneLoaded(Game, Single)
LoadingExtension.ctor() static
LoadingExtension.ctor() instance
LoadingExtension.OnCreated(...):
 - Mode: Game
 - Theme: Europe
 - Complete: False
+ LoadingManager.instance.m_metaDataReady
ThreadingExtension.ctor() static
ThreadingExtension.ctor() instance
ThreadingExtension.OnCreated(...)
SceneManager.sceneLoaded(EuropeLoading2, Additive)
SceneManager.sceneLoaded(EuropePrefabs, Additive)
// etc...
SceneManager.sceneLoaded(FestivalPrefabs, Additive)
SceneManager.sceneLoaded(EuropeProperties, Additive)
UserMod.OnSettingsUI()
SceneManager.sceneLoaded(Ingame, Additive)
+ LoadingManager.instance.m_simulationDataReady
+ LoadingManager.instance.m_levelLoaded(NewGameFromMap)
LoadingExtension.OnLevelLoaded(NewGame)
LoadingExtension.OnLevelUnloading()
LoadingExtension.OnReleased()
ThreadingExtension.OnReleased()
UserMod.OnDisabled()
```

Not sure why it didn't work for Elektrix.

**Comment by originalfoo** [comment]
Elektrix was using an older local verison which for some reason didn't generate events.
