### ISSUE TITLE
OnAssetLoaded is not called

### ISSUE THREAD

**Issue by Strdate** [thale5/LSM#3]
Hi, the game provides interface for all mods which notifies them when an asset is loaded.
`IAssetDataExtension`

`public void OnAssetLoaded(string name, object asset, Dictionary<string, byte[]> userData)`
But when your mod is enabled, this method is never called. Unfortunately there are not many mods (maybe no mod at all?) which would need this functionality, but it's an unpleasant surprise when you are creating a mod which would use this.
It would be nice if you could look at this! :)

**Comment by thale5** [comment]
Mod updated so that IAssetDataExtensions are called for all assets.
